language: csharp
mono: alpha
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
env:
    - MONO_TLS_PROVIDER=legacy
script: ./build.sh --verbosity=minimal
notifications:
  email:
    - nancy@nancyfx.org
